version: '2'

name: expandable-application

services:

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    container_name: expandable-application-proxy
    ports:
      - "8080:80"
    volumes:
      - ./proxy/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    depends_on:
      - auth

  auth:
    build:
      context: ./auth
      dockerfile: docker/Dockerfile
    container_name: expandable-application-auth
    restart: always
    depends_on:
      - db

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: expandable-application-db
    restart: always
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data: